### ISSUE TITLE
CLI Befehl "chef execute <<Simulationsschritt>>.py" implementieren

### ISSUE THREAD

**Issue by SophieAltenburg** [EMS-TU-Ilmenau/chefkoch#16]
Es soll möglich sein von der Command Line aus eine Python Datei auszuführen, die folgendes Format hat:
- Input ist ein Dictionary. In diesem sind die eventuell einzelnen Inputvariablen und -werte enthalten.
- Output ist ein Dictionary, wieder {"output_variablen_name": Wert}.
- Es enthält eine Function mit dem Namen def execute(**args), die keine weiteren Parameter abgesehen von dem Input-Dictionary nimmt.

Für die Ausführung ist folgender Plan vorgesehen:
1. chef erstellt eine temporäre Datei mit allen bisher diesen Schritt beeinflussenden Parametern als .json
2. Aus dem Recipe wird das Mapping Funktionsargument & Namespaceeintrag bestimmt
3. CLI: chef execute $step $mapping
bsp.: chef execute step.py a=var_a  b=var_c  c=bla.blub.d
4. Hashing der Eingabewerte wird durchgeführt
5. chef benennt temporäre Parameter- und Ergebnisdatei mit dem erzeugten Hashwert um. Verlinkt evt. auf andere Ergebisse. (Zur Not im Wiki in der BA nachlesen.)

**Comment by wiebsS** [comment]
step is executed, but not from commandline
not sure, if this would be a necessary feature
