### ISSUE TITLE
Sanity Check für Simulationsschritte

### ISSUE THREAD

**Issue by SophieAltenburg** [EMS-TU-Ilmenau/chefkoch#17]
Die Simulationsschritte sollen als Python Datei hinterlegt werden, die ein Dictionary als Input nimmt (in dem dann alle tatsächlich benötigten Inputs drin stehen), ein Dictionary als Output raus gibt und eine Funktion execute(**args) definiert. Wenn der Speicherort der Simulationsschritte in die Console eingegeben wird, soll ein Sanity Check durchgeführt werden, der prüft, ob sie dieses Format haben und ob die Dictionaries mit ihren Key-Namen mit dem entsprechenden Schritt/Knoten im Recipe übereinstimmt.

**Comment by wiebsS** [comment]
done
