### ISSUE TITLE
Eine Graph Library für das Recipe verwenden

### ISSUE THREAD

**Issue by SophieAltenburg** [EMS-TU-Ilmenau/chefkoch#18]
1. Recipe soll von list erben, so dass man nicht jedes mal `recipe.nodes` schreiben muss, sondern recipe[0] verwenden kann und man nodes per Index adressieren kann.

2. Auf den Anhängigkeiten im Recipe wird Tiefensuche verwendet, um sicher zu stellen, dass es keine Abhängigkeits-Kreise gibt. Diese Tiefensuche ist bisher selbst implementiert und nicht besonders effizient. Stattdessen soll der Inhalt des Recipes als gerichteter Graph dargestellt werden und die Graph-Library eigene Tiefensuche oder direkt kreisfreiheit verwendet werden, die vermutlich effizienter und im Code definitiv leichter zu lesen ist. Später bei der Ausführung des recipes wird das ebenfalls nützlich.

**Comment by ChristophWWagner** [comment]
Empfehlung von @Thosse bezüglich Graph Libraries:
 * `sagemath` ist eine full-blown Bibliothek zur Repräsentation und dem Umgang mit Graphen in Python3
 * ... kann Graphen auch plotten, wenn man angibt um was für eine Art Graph es sich handelt
 * ... bietet eine Vielzahl von Checks und Operationen auf Graphen, die auch sehr effizient implementiert sind
 * Eventuell könnten Flussalgorithmen bei der Recipeverarbeitung von Chefkoch helfen? Stichwort "Quelle, Senke", "ganzzahliger Fluss"
 * "Ford Fulkerson Algorithmus"

**Comment by SebastianSemper** [comment]
Ich kann mir nicht vorstellen, dass man ein Recipe aufbaut, sodass selbst
ein ineffizient implementierter DFS oder BFS Algorithmus ein Problem wird.
Deshalb e für mich eher das Argument zu sage zu wechseln, dass sie ihren
Code sicher besser testen und maintainen. Change my Mind.

**Comment by wiebsS** [comment]
we use the graph-library [grap-theory](https://pypi.org/project/graph-theory/)
