### ISSUE TITLE
Funktion, die Recipe-Werte im Flavour-Objekt nachschauen kann

### ISSUE THREAD

**Issue by SophieAltenburg** [EMS-TU-Ilmenau/chefkoch#19]
Im Recipe sind als Inputs für manche Simulationsschritte Flavour-Parameter angegeben. Bisher werden sie mit {"input1": "flavour.parametername"} angegeben. Jetzt sollen sie nur noch als {"input1": "parametername"} angegeben werden. Bei der Überprüfung des Recipes inputIntegrity() soll geprüft werden, ob ein Parametername im Flavour Objekt vorhanden ist und falls ja als korrekt angesehen werden, statt dass wie bisher nur auf das Präfix "flavour." geachtet wird.

**Comment by makley273** [comment]
@SophieAltenburg  soll dazu im recipe auf ein bestimmtes Flavour Objekt verwiesen werden, oder bekommt der Input einen Prefix mit dem entsprechenden Flavour Objekt, oder wie sollte am besten das Flavour referenziert werden?

**Comment by wiebsS** [comment]
Flavours can be found over the fridge
The fridge manages the different items and flavours are stored in flavour-shelfs
