### ISSUE TITLE
Complete concept of parameter handling

### ISSUE THREAD

**Issue by SophieAltenburg** [EMS-TU-Ilmenau/chefkoch#30]
a.k.a Consistent handling of Command line (frontend) and call (backend) Arguments 

The user interface for chefkoch is a command line tool, therefore information like "What is the workflow of the simulation?" need to be entered as command line arguments, for example the file path of the recipe. Thise configuration information might be collected in a "cheffile", that holds default file paths for the recipe, flavour file, the cache folder etc. The "kitchenfile" might specify which hardware can be used to execute a simulation, for example "How many processes can be run in parallel?", "How many cores are available?" or "Should the compute cluster be used for execution?"

Still, this first prototype does not use concurrency.
- [x] Should the "kitchen file" be planned and "emptily" included now or is it irrelevant for now?
- [x] Is the "cheffile" needed or unnecessary overhead?
- [x] Which information should be included in the "cheffile"?
- [x] How is this information given to the backend of the chefkoch? Central config file? Minimal database?

**Comment by SophieAltenburg** [comment]
Wild berry labels :'D

**Comment by wiebsS** [comment]
The information are stored in a config-file in a JSON-Container

The cheffile contains the options, the resources, the different flavours, a kitchen file, the recipe, and links
