### ISSUE TITLE
Full Specification of data formats for the definitions of: Recipes Steps Flavours

### ISSUE THREAD

**Issue by SophieAltenburg** [EMS-TU-Ilmenau/chefkoch#31]
- [x] Recipe found in sphinx documentation, weak spot: how are steps entered?
- [x] Flavour file in sphinx documentation
- [ ] Steps:
  * How can steps be entered?
  * Where are they saved?
  * How can they be executed

Look up step definition in bachelor thesis and evaluate if it makes sense for this prototype. Also give definition of CLI command, idea of execution and specification.

**Comment by wiebsS** [comment]
Steps are entered in the recipe
They are represented by the step-class and have an execute-function
