### ISSUE TITLE
Der PyCodeStyle-Check und der Code-Formatter "black" sollen sich nicht widersprechen 

### ISSUE THREAD

**Issue by SophieAltenburg** [EMS-TU-Ilmenau/chefkoch#49]
Bis jetzt kann black von der Travis Continuous Integration im Makefile nicht verwendet werden, da `make black` in einer Aufzählung der Form:

```python
somelist = [
    {"smells": "like", "teen": "spirit", },
    {"has": "a", "funny": "story", },
]
```

Leerzeichen hinter dem letzen Komma weg nimmt, PyCodeStyle aber einen "missing whitespace after comma" Fehler schmeißt und die Continuous Integration Tests dann einen merge blockieren.
Aufgabe: Recherchieren, welche PyCodeStyle Regel das ist oder welche Regel bei black und eine von beiden ausschließen.

**Comment by SebastianSemper** [comment]
Bei mir funktioniert das im makefile ganz gut:

```
.PHONY: black
black:
	black -l79 demo/*.py eadf/*.py test/*.py *.py doc/source/*.py
.PHONY: stylecheck
stylecheck:
	pycodestyle --max-line-length=80 --statistics --ignore=E203,W503 eadf/*.py test/*.py demo/*.py *.py
```

**Comment by SophieAltenburg** [comment]
Das sind genau die gleichen Definitionen wie bei uns.

**Comment by SophieAltenburg** [comment]
Dann ist die Lösung wohl, keine überflüssigen Kommata mehr zu setzen.
